### ISSUE TITLE
Entire application crashes when you try to swipe back.

### ISSUE THREAD

**Issue by jdhouti** [juliendhouti/Dame#21]
This is probably a mac specific issue. Here's what happens:

![ezgif-3-5f0e01b164](https://user-images.githubusercontent.com/22134400/28188973-de2e6384-67d8-11e7-8647-8de819cb06b9.gif)

The error:
```Traceback (most recent call last):
  File "frontend2.py", line 266, in <module>
    root.mainloop()
  File "/Volumes/SWIFT/Applications/anaconda/lib/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by tjbencomo** [comment]
https://stackoverflow.com/questions/16995969/inertial-scrolling-in-mac-os-x-with-tkinter-and-python
This might have some possible solutions especially the try/except answer at the bottom
