### ISSUE TITLE
Picking Scatter Plot Columns

### ISSUE THREAD

**Issue by tjbencomo** [juliendhouti/Dame#5]
Before you try opening a file, you must go into the code in frontend.py and specify which columns you would like to use when get_scatter_plot() is called. Its on line 49

**Comment by jdhouti** [comment]
Okay but when a user wants to use that aspect of the program, it's safe to assume he/she doesn't know how to do that. I'm going to assume that you just meant to do that for now until you add the option of requesting that kind of input from the user.
